name: src_cloud_mobile
description: SRC Cloud — mobile app for iOS & Android
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.4.3
  flutter_secure_storage: ^9.2.2
  provider: ^6.1.2
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.2
  intl: ^0.19.0
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
